name: Daily Update

on: push

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo content
        uses: actions/checkout@v2

      - name: Setup python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Install dependencies
        run: |
          pip install pandas
          pip install TableauScraper

      - name: Execute Script
        run: |
          python script/data_periode.py
          echo "data_periode.py Done"

          python script/data_master.py
          echo "data_master.py Done"

      - name: Commit File
        run: |
          git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git add .
          now=$(date)
          git commit -m "Auto Commit $now"

      - name: Push Changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ github.ref }}
